-- =============================================================================
-- Phase 13: CTGAN Behavioral Simulator — Synthetic Session Storage
-- File:    infra/clickhouse/sql/007_synthetic_sessions.sql
-- Applies: v2.0 — Synthetic Data Generation
-- Safe to run multiple times (CREATE TABLE IF NOT EXISTS).
-- DO NOT modify prior migration files.
-- =============================================================================
--
-- Creates one MergeTree table:
--   1. analytics.synthetic_sessions — CTGAN-generated session rows
--
-- Design decisions:
--   - Schema mirrors analytics.session_features (Phase 9) so the two sources
--     are structurally interchangeable for Phase 18 augmented training.
--   - first_event_at / last_event_at are omitted: they are meaningful for real
--     sessions (wall-clock span of activity) but are not generated by CTGAN
--     and would be misleading synthetic timestamps.
--   - primary_category is a derived field not present in session_features.
--     It captures the dominant category of the session (Retailrocket category_id
--     or live tracker category string) and is the conditional sampling axis for
--     Phase 17 product-level predictions.
--   - source is always 'synthetic'; is_synthetic = 1 is a redundant guard kept
--     so that a SELECT * FROM analytics.synthetic_sessions UNION ALL SELECT * FROM
--     analytics.session_features query can filter by source OR is_synthetic.
--   - ml_lead_score and ml_score_tier are populated by generate_synthetic_sessions.py
--     (Phase 11 MLScorer applied at generation time). They are nullable — a row
--     with no score means the scorer was not run (e.g., --dry-run mode).
--   - MergeTree (not ReplacingMergeTree) because the overwrite path truncates
--     the table before re-inserting, making dedup-on-key unnecessary.
--   - ORDER BY (session_id) keeps point-lookups fast; PhysicalGroupBy is the
--     primary consumer pattern.
-- =============================================================================

CREATE TABLE IF NOT EXISTS analytics.synthetic_sessions
(
    -- session identity (mirrored from session_features)
    session_id                String,
    anonymous_user_id         String,

    -- behavioral feature vector (must match MLScorer._FEATURE_COLS + extras)
    page_views                UInt64,
    product_views             UInt64,
    add_to_cart_count         UInt64,
    purchase_count            UInt64,
    search_count              UInt64,
    max_scroll_pct            Nullable(Float32),   -- NULL = no scroll data (as in Retailrocket)
    session_duration_seconds  UInt32,
    distinct_products_viewed  UInt64,
    cart_abandoned            UInt8,               -- 0 or 1

    -- category axis for Phase 17 conditional sampling
    -- string representation of Retailrocket category_id (e.g. '213') or
    -- live tracker category name; '' when unknown
    primary_category          LowCardinality(String),

    -- provenance columns
    source                    LowCardinality(String) DEFAULT 'synthetic',
    is_synthetic              UInt8 DEFAULT 1,

    -- ML scoring tags (populated by generate_synthetic_sessions.py)
    ml_lead_score             Nullable(Float32),   -- calibrated probability [0, 1]
    ml_score_tier             LowCardinality(String) DEFAULT '',

    -- generation timestamp
    generated_at              DateTime DEFAULT now()
)
ENGINE = MergeTree()
ORDER BY (session_id)
SETTINGS index_granularity = 8192;
